### ISSUE TITLE
Oauth logins sometimes result in KeyError 'login' exception.

### ISSUE THREAD

**Issue by ukanga** [onaio/superset-patchup#47]
```python
Traceback (most recent call last):
  File "/home/superset/.virtualenvs/superset/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/superset/.virtualenvs/superset/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/superset/.virtualenvs/superset/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/superset/.virtualenvs/superset/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/superset/.virtualenvs/superset/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/superset/.virtualenvs/superset/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/superset/.virtualenvs/superset/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/superset/.virtualenvs/superset/lib/python3.6/site-packages/superset_patchup/oauth.py", line 120, in oauth_authorized
    resp = self.appbuilder.sm.oauth_remotes[provider].authorized_response()
KeyError: 'login'
```

**Comment by ukanga** [comment]
We seem to be using `redirect("login")` which does result in a redirect to `/oauth-authorized/login`. We do not have an oauth2 config with `login` hence the exception. I think the intention is to redirect to `/login` instead. A `redirect("/login")` should address the issue.
